Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"

  config.vm.provider "virtualbox" do |virtualbox|
    virtualbox.cpus = 1
    virtualbox.memory = 1024
  end

  config.vm.define "icaharelS" do |server|
    server.vm.hostname = "icaharelS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provision "shell", path: "scripts/vm_setup.sh"


    server.vm.provider "virtualbox" do |virtualbox|
      virtualbox.name = "icaharelS"
    end
  end
end
