# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04" #image de base des vm
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |virtualbox| #configure materiel requis
    virtualbox.cpus = 1
    virtualbox.memory = 1024
  end

  config.vm.define "icaharelS" do |server| #déclare création vm server
    server.vm.hostname = "icaharelS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provision "shell", path: "scripts/server.sh"

    server.vm.provider "virtualbox" do |virtualbox| 
      virtualbox.name = "icaharelS"
    end
  end

  config.vm.define "icaharelSW" do |worker| #déclare création vm worker
    worker.vm.hostname = "icaharelSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provision "shell", path: "scripts/worker.sh"

    worker.vm.provider "virtualbox" do |virtualbox|
      virtualbox.name = "icaharelSW"
    end
  end
end
